Repository Willardstation/tg-voidcrew, pull requests merged in 2022-12, with the labels that each got.

#50 overmap now loads correctly
  _maps/voidcrew/ship_box.dmm
  _maps/voidcrew/ship_nano_phalanx.dmm
  _maps/voidcrew/ship_osprey.dmm
  tgstation.dme
  voidcrew/_DEFINES/overmap.dm
  voidcrew/_DEFINES/subsystems.dm
  voidcrew/edits/map_config.dm
  voidcrew/edits/mobs/new_player.dm
  voidcrew/mapping/_mapping.dm
  voidcrew/mapping/areas.dm
  voidcrew/mapping/docking_port/_docking.port.dm
  voidcrew/mapping/shuttles/_shuttle.dm
  voidcrew/mapping/shuttles/box.dm
  voidcrew/modules/antagonist/_locate_weakpoint.dm
  voidcrew/modules/cryo/console.dm
  voidcrew/modules/cryo/machine.dm
  voidcrew/modules/overmap/code/controllers/subsystem/overmap.dm
  voidcrew/modules/overmap/code/controllers/subsystem/shuttle.dm
  voidcrew/modules/overmap/code/game/turfs/closed/overmap.dm
  voidcrew/modules/overmap/code/game/turfs/open/overmap.dm
  voidcrew/modules/overmap/code/modules/overmap/ship.dm
  voidcrew/modules/shuttle/engine/fuel.dm
  voidcrew/modules/shuttle/engine/fueled_heater.dm
  voidcrew/modules/shuttle/helm/_helm.dm
Labels: Required Feature

#53 Fixes and improves cryogenic chamber and control
  tgui/packages/voidcrew_tgui/interfaces/CryoStorageConsole.js
  voidcrew/mapping/docking_port/_docking.port.dm
  voidcrew/modules/cryo/console.dm
  voidcrew/modules/cryo/machine.dm
  voidcrew/modules/nanites/code/items/items.dm
  voidcrew/modules/nanites/code/machines/nanite_chamber.dm
  voidcrew/modules/nanites/code/machines/nanite_chamber_control.dm
  voidcrew/modules/nanites/code/machines/public_chamber.dm
  voidcrew/modules/overmap/code/modules/overmap/ship.dm
  voidcrew/modules/shuttle/engine/fueled_heater.dm
  voidcrew/modules/shuttle/engine/liquid.dm
  voidcrew/modules/shuttle/engine/shuttle_engine.dm
  voidcrew/modules/shuttle/helm/_helm.dm
Labels: Fix

#62 Makes the game compile again.
  voidcrew/modules/nanites/code/programs/utility.dm
Labels: Fix

#63 Kills the Syndicate Headsets
  _maps/voidcrew/ship_luxembourg.dmm
  _maps/voidcrew/ship_syndicate_geneva.dmm
  voidcrew/modules/outfits/syndicate.dm
Labels: Request

#32 Removes unwanted subsystems
  tgstation.dme
  voidcrew/edits/config.dm
  voidcrew/edits/subsystem/_subsystem.dm
Labels: Required Feature, Fix
